### ISSUE TITLE
write benchmarking program

### ISSUE THREAD

**Issue by iwanbk** [g8os/fs#2]
As described in https://github.com/g8os/home/issues/3#issuecomment-190585453
```
e.g. use the RW feature, write lots of small files
same for R feature , open all files & read them see why slow
compare with same test on native FS
```

**Comment by iwanbk** [comment]
need to make some improvement.

**Comment by iwanbk** [comment]
done, PR is ready again

**Comment by despiegk** [comment]
Did we find something?

------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

On March 2, 2016 at 3:02:45 PM, Iwan Budi Kusnanto (notifications@github.com) wrote:

done, PR is ready again

**Comment by iwanbk** [comment]
@despiegk 
yes, https://github.com/g8os/home/issues/3#issuecomment-191196211
For read operation, it seems that bottleneck is in the code that send data from our driver to user app.
I think it is worth to try hanwen/go-fuse, it is binding for libfuse (C lib).
